# Generated by Django 3.2.3 on 2021-06-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ota_app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='price',
            name='date',
        ),
        migrations.RemoveField(
            model_name='price',
            name='rateplan',
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('availability', models.SmallIntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ota_app2.price')),
                ('rateplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ota_app2.rateplan')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='rateplan',
            field=models.ManyToManyField(through='ota_app2.Availability', to='ota_app2.Rateplan'),
        ),
    ]
