# Generated by Django 3.2.3 on 2021-06-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ota_app2', '0002_auto_20210608_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='availability',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.RemoveField(
            model_name='price',
            name='rateplan',
        ),
        migrations.AddField(
            model_name='price',
            name='rateplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ota_app2.rateplan'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
