# Generated by Django 3.2.3 on 2021-06-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ota_app2', '0004_alter_price_rateplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('date', 'rateplan')},
        ),
    ]
